# Generated by Django 4.2.3 on 2023-08-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("breed", models.CharField(max_length=20)),
                ("behavior", models.TextField(max_length=250)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
