# Generated by Django 4.2.3 on 2023-08-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_dog_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="breed",
            field=models.CharField(max_length=50),
        ),
    ]
