# Generated by Django 4.2.3 on 2023-08-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_playdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tricks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            ("1", "Very Easy"),
                            ("2", "Easy"),
                            ("3", "Medium"),
                            ("4", "Hard"),
                            ("5", "Very Hard"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="playdate",
            name="length",
            field=models.IntegerField(verbose_name="How many hours"),
        ),
    ]
