# Generated by Django 4.2.3 on 2023-08-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_tricks_alter_playdate_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="tricks",
            name="items",
            field=models.BooleanField(default=False),
        ),
    ]
