# Generated by Django 4.2.3 on 2023-08-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_rename_tricks_trick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trick",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("VE", "Very Easy"),
                    ("E", "Easy"),
                    ("M", "Medium"),
                    ("H", "Hard"),
                    ("VH", "Very Hard"),
                ],
                default="vh",
                max_length=2,
            ),
        ),
    ]
