# Generated by Django 4.2.3 on 2023-08-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0008_alter_trick_difficulty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trick",
            name="items",
        ),
        migrations.AddField(
            model_name="dog",
            name="tricks",
            field=models.ManyToManyField(to="main_app.trick"),
        ),
    ]
